# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 550)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(0, 0, 521, 91))
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(600, 10, 101, 101))
        self.homeButton.setAutoFillBackground(False)
        self.homeButton.setText("")
        self.homeButton.setIconSize(QtCore.QSize(101, 101))
        self.homeButton.setObjectName("homeButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton.setGeometry(QtCore.QRect(600, 150, 101, 101))
        self.plusButton.setText("")
        self.plusButton.setIconSize(QtCore.QSize(101, 101))
        self.plusButton.setObjectName("plusButton")
        self.statButton = QtWidgets.QPushButton(self.centralwidget)
        self.statButton.setGeometry(QtCore.QRect(600, 290, 101, 101))
        self.statButton.setText("")
        self.statButton.setIconSize(QtCore.QSize(101, 101))
        self.statButton.setObjectName("statButton")
        self.commentText = QtWidgets.QTextEdit(self.centralwidget)
        self.commentText.setGeometry(QtCore.QRect(100, 220, 201, 71))
        self.commentText.setObjectName("commentText")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 130, 201, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.amountLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.amountLine.setObjectName("amountLine")
        self.verticalLayout.addWidget(self.amountLine)
        self.categoryLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.categoryLine.setObjectName("categoryLine")
        self.verticalLayout.addWidget(self.categoryLine)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 130, 61, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.moneyLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.moneyLabel.setObjectName("moneyLabel")
        self.verticalLayout_2.addWidget(self.moneyLabel)
        self.categoryLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.categoryLabel.setObjectName("categoryLabel")
        self.verticalLayout_2.addWidget(self.categoryLabel)
        self.commentLabel = QtWidgets.QLabel(self.centralwidget)
        self.commentLabel.setGeometry(QtCore.QRect(10, 210, 81, 51))
        self.commentLabel.setObjectName("commentLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.moneyLabel.setText(_translate("MainWindow", "Сумма:"))
        self.categoryLabel.setText(_translate("MainWindow", "Категория:"))
        self.commentLabel.setText(_translate("MainWindow", "Комментарий:"))
