# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_post_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPost_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(419, 403)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 370, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.createCategoryButton = QtWidgets.QPushButton(Dialog)
        self.createCategoryButton.setGeometry(QtCore.QRect(10, 300, 161, 23))
        self.createCategoryButton.setObjectName("createCategoryButton")
        self.createSubCategoryButton = QtWidgets.QPushButton(Dialog)
        self.createSubCategoryButton.setGeometry(QtCore.QRect(250, 300, 161, 23))
        self.createSubCategoryButton.setObjectName("createSubCategoryButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 401, 281))
        self.groupBox.setStyleSheet("QGroupBox {\n"
                                    "margin-top: 2ex;\n"
                                    "}\n"
                                    "QGroupBox:enabled {\n"
                                    "border: 2px solid black;\n"
                                    "border-radius: 5px;\n"
                                    "}\n"
                                    "QGroupBox::title {\n"
                                    "subcontrol-origin: margin;\n"
                                    " left: 3ex;\n"
                                    " }\n"
                                    "")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.commentText = QtWidgets.QTextEdit(self.groupBox)
        self.commentText.setGeometry(QtCore.QRect(220, 160, 161, 71))
        self.commentText.setObjectName("commentText")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 20, 160, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.amountLine = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.amountLine.setObjectName("amountLine")
        self.verticalLayout_2.addWidget(self.amountLine)
        self.categoryBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.categoryBox.setObjectName("categoryBox")
        self.verticalLayout_2.addWidget(self.categoryBox)
        self.subCategoryBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.subCategoryBox.setObjectName("subCategoryBox")
        self.verticalLayout_2.addWidget(self.subCategoryBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 156, 17))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 131, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.createCategoryButton.setText(_translate("Dialog", "Создать категорию"))
        self.createSubCategoryButton.setText(_translate("Dialog", "Создать подкатегорию"))
        self.label_3.setText(_translate("Dialog", "Комментарий(необязательно):"))
        self.label.setText(_translate("Dialog", "Введите сумму:"))
        self.label_2.setText(_translate("Dialog", "Введите категорию:"))
        self.label_4.setText(_translate("Dialog", "Введите подкатегорию:"))
