# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_post_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPost_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(483, 355)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(160, 310, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.amountLine = QtWidgets.QLineEdit(Dialog)
        self.amountLine.setGeometry(QtCore.QRect(180, 70, 141, 20))
        self.amountLine.setObjectName("amountLine")
        self.categoryLine = QtWidgets.QLineEdit(Dialog)
        self.categoryLine.setGeometry(QtCore.QRect(180, 120, 141, 20))
        self.categoryLine.setObjectName("categoryLine")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 70, 81, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 161, 20))
        self.label_3.setObjectName("label_3")
        self.commentText = QtWidgets.QTextEdit(Dialog)
        self.commentText.setGeometry(QtCore.QRect(180, 170, 141, 71))
        self.commentText.setObjectName("commentText")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Введите сумму:"))
        self.label_2.setText(_translate("Dialog", "Введите категорию:"))
        self.label_3.setText(_translate("Dialog", "Комментарий(необязательно):"))
