# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_type_statistic.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Choose_Type_Statistic_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 214)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 20, 181, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.analyseButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.analyseButton.setEnabled(True)
        self.analyseButton.setMinimumSize(QtCore.QSize(0, 40))
        self.analyseButton.setObjectName("analyseButton")
        self.verticalLayout.addWidget(self.analyseButton)
        self.diagramButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.diagramButton.setMinimumSize(QtCore.QSize(0, 40))
        self.diagramButton.setObjectName("diagramButton")
        self.verticalLayout.addWidget(self.diagramButton)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 50, 181, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 171, 21))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.analyseButton.setText(_translate("Dialog", "Статистика"))
        self.diagramButton.setText(_translate("Dialog", "Диаграмма"))
        self.label.setText(_translate("Dialog", "Анализ за год/месяц/неделю:"))
        self.label_2.setText(_translate("Dialog", "Диагламма расходов:"))
