# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistic_analyse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Statistic_Analyse_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(713, 706)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 670, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.PlotWidget = PlotWidget(Dialog)
        self.PlotWidget.setGeometry(QtCore.QRect(0, 0, 711, 461))
        self.PlotWidget.setObjectName("PlotWidget")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 470, 691, 181))
        self.groupBox.setStyleSheet("QGroupBox {\n"
                                    "margin-top: 2ex;\n"
                                    "}\n"
                                    "QGroupBox:enabled {\n"
                                    "border: 2px solid black;\n"
                                    "border-radius: 5px;\n"
                                    "}\n"
                                    "QGroupBox::title {\n"
                                    "subcontrol-origin: margin;\n"
                                    " left: 3ex;\n"
                                    " }\n"
                                    "")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(150, 60, 521, 91))
        self.textBrowser.setStyleSheet("border: 1px solid black;\n"
                                       "border-radius: 1px;\n"
                                       "")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(150, 27, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Периоды времени:"))
        self.comboBox.setItemText(0, _translate("Dialog", "Месяца"))
        self.comboBox.setItemText(1, _translate("Dialog", "Недели"))
        self.comboBox.setItemText(2, _translate("Dialog", "Дни"))
        self.label_2.setText(_translate("Dialog", "Вердикт:"))


from pyqtgraph import PlotWidget
